
development:
  adapter: postgresql
  encoding: unicode
  database: student-admin-app
  host: localhost
  pool: 5
  username: rails_user
  password: rails_user

production:
  adapter: postgresql
  encoding: unicode
  database: student-admin-app
  host: localhost
  pool: 5
  username: rails_user
  password: rails_user



